# Generated by Django 4.2.1 on 2023-05-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_book_isbn_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(to='home.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='General', max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, unique=True),
        ),
    ]
